-- MySQL Script generated by MySQL Workbench
-- Wed Oct 19 22:21:31 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Personagem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Personagem` (
  `id_personagem` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `raca` VARCHAR(45) NOT NULL,
  `genero` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_personagem`),
  UNIQUE INDEX `id_personagem_UNIQUE` (`id_personagem` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Equipe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Equipe` (
  `id_equipe` INT NOT NULL AUTO_INCREMENT,
  `nome_equipe` VARCHAR(45) NOT NULL,
  `experiencia` VARCHAR(45) NULL,
  `total_de_membros` INT GENERATED ALWAYS AS () VIRTUAL,
  PRIMARY KEY (`id_equipe`),
  UNIQUE INDEX `id_equipe_UNIQUE` (`id_equipe` ASC) VISIBLE,
  UNIQUE INDEX `nome_equipe_UNIQUE` (`nome_equipe` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Aventureiro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Aventureiro` (
  `id_aventureiro` INT NOT NULL AUTO_INCREMENT,
  `nivel` INT NOT NULL,
  `classe` VARCHAR(45) NOT NULL,
  `subclasse` VARCHAR(45) NULL,
  `rank_guilda` INT NOT NULL,
  `equipe` INT NULL,
  PRIMARY KEY (`id_aventureiro`),
  UNIQUE INDEX `id_aventureiro_UNIQUE` (`id_aventureiro` ASC) VISIBLE,
  INDEX `fk_Aventureiro_Equipe1_idx` (`equipe` ASC) VISIBLE,
  CONSTRAINT `id_aventureiro`
    FOREIGN KEY (`id_aventureiro`)
    REFERENCES `mydb`.`Personagem` (`id_personagem`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Aventureiro_Equipe1`
    FOREIGN KEY (`equipe`)
    REFERENCES `mydb`.`Equipe` (`id_equipe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Operario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Operario` (
  `id_operario` INT NOT NULL AUTO_INCREMENT,
  `nivel_maestria` INT NOT NULL,
  `Personagem_id_personagem` INT NOT NULL,
  PRIMARY KEY (`id_operario`, `Personagem_id_personagem`),
  UNIQUE INDEX `id_operario_UNIQUE` (`id_operario` ASC) VISIBLE,
  CONSTRAINT ``
    FOREIGN KEY (`id_operario`)
    REFERENCES `mydb`.`Personagem` (`id_personagem`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Mercador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Mercador` (
  `id_mercador` INT NOT NULL,
  PRIMARY KEY (`id_mercador`),
  CONSTRAINT `fk_Mercador_Operario`
    FOREIGN KEY (`id_mercador`)
    REFERENCES `mydb`.`Operario` (`id_operario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Mercadoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Mercadoria` (
  `id_mercadoria` INT NOT NULL,
  `preco` FLOAT NOT NULL,
  `nome_produto` VARCHAR(45) NOT NULL,
  `raridade` VARCHAR(45) NOT NULL,
  UNIQUE INDEX `nome_produto_UNIQUE` (`nome_produto` ASC) VISIBLE,
  PRIMARY KEY (`id_mercadoria`),
  UNIQUE INDEX `id_mercadoria_UNIQUE` (`id_mercadoria` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ferreiro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ferreiro` (
  `id_ferreiro` INT NOT NULL,
  PRIMARY KEY (`id_ferreiro`),
  CONSTRAINT `fk_Ferreiro_Operario1`
    FOREIGN KEY (`id_ferreiro`)
    REFERENCES `mydb`.`Operario` (`id_operario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Equipamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Equipamento` (
  `id_equipamento` INT NOT NULL,
  `aventureiro_dono` INT NOT NULL,
  `armadura` VARCHAR(45) NULL,
  `arma` VARCHAR(45) NULL,
  `ferreiro_resp` INT NULL,
  INDEX `fk_Equipamento_Aventureiro1_idx` (`aventureiro_dono` ASC) VISIBLE,
  PRIMARY KEY (`id_equipamento`, `aventureiro_dono`),
  INDEX `fk_Equipamento_Ferreiro1_idx` (`ferreiro_resp` ASC) VISIBLE,
  CONSTRAINT `fk_Equipamento_Aventureiro1`
    FOREIGN KEY (`aventureiro_dono`)
    REFERENCES `mydb`.`Aventureiro` (`id_aventureiro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Equipamento_Ferreiro1`
    FOREIGN KEY (`ferreiro_resp`)
    REFERENCES `mydb`.`Ferreiro` (`id_ferreiro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Contratante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Contratante` (
  `id_contratante` INT NOT NULL AUTO_INCREMENT,
  `nome_contratante` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_contratante`),
  UNIQUE INDEX `id_contratante_UNIQUE` (`id_contratante` ASC) VISIBLE,
  UNIQUE INDEX `nome_contratante_UNIQUE` (`nome_contratante` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Missao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Missao` (
  `id_missao` INT NOT NULL,
  `titulo_missao` VARCHAR(45) NOT NULL,
  `recompensa` VARCHAR(45) NOT NULL,
  `categoria` VARCHAR(45) NULL,
  `contratante` INT NOT NULL,
  PRIMARY KEY (`id_missao`),
  UNIQUE INDEX `id_missao_UNIQUE` (`id_missao` ASC) VISIBLE,
  INDEX `fk_Missao_Contratante1_idx` (`contratante` ASC) VISIBLE,
  CONSTRAINT `fk_Missao_Contratante1`
    FOREIGN KEY (`contratante`)
    REFERENCES `mydb`.`Contratante` (`id_contratante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`contrato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`contrato` (
  `id_equipe` INT NOT NULL,
  `id_contratante` INT NOT NULL,
  `id_missao` INT NOT NULL,
  PRIMARY KEY (`id_equipe`, `id_contratante`, `id_missao`),
  INDEX `fk_contrato_Contratante1_idx` (`id_contratante` ASC) VISIBLE,
  INDEX `fk_contrato_Missao1_idx` (`id_missao` ASC) VISIBLE,
  CONSTRAINT `fk_contrato_Equipe1`
    FOREIGN KEY (`id_equipe`)
    REFERENCES `mydb`.`Equipe` (`id_equipe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_contrato_Contratante1`
    FOREIGN KEY (`id_contratante`)
    REFERENCES `mydb`.`Contratante` (`id_contratante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_contrato_Missao1`
    FOREIGN KEY (`id_missao`)
    REFERENCES `mydb`.`Missao` (`id_missao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`venda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`venda` (
  `id_mercador` INT NOT NULL,
  `id_mercadoria` INT NOT NULL,
  PRIMARY KEY (`id_mercador`, `id_mercadoria`),
  INDEX `fk_Mercador_has_Mercadoria_Mercadoria1_idx` (`id_mercadoria` ASC) VISIBLE,
  INDEX `fk_Mercador_has_Mercadoria_Mercador1_idx` (`id_mercador` ASC) VISIBLE,
  CONSTRAINT `fk_Mercador_has_Mercadoria_Mercador1`
    FOREIGN KEY (`id_mercador`)
    REFERENCES `mydb`.`Mercador` (`id_mercador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Mercador_has_Mercadoria_Mercadoria1`
    FOREIGN KEY (`id_mercadoria`)
    REFERENCES `mydb`.`Mercadoria` (`id_mercadoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
